#
# Copyright Siemens AG, 2017. Part of the SW360 Portal Project.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved. This file is offered as-is,
# without any warranty.
#

sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - curl -o datahandler-3.1.0-SNAPSHOT.jar https://s3.amazonaws.com/sw360restdoc/datahandler-3.1.0-SNAPSHOT.jar
  - mvn install:install-file -Dfile=datahandler-3.1.0-SNAPSHOT.jar -DgroupId=org.eclipse.sw360 -DartifactId=datahandler -Dversion=3.1.0-SNAPSHOT -Dpackaging=jar

install: true

script:
  - ./gradlew build

deploy:
  provider: s3
  access_key_id: "$ARTIFACTS_KEY"
  secret_access_key: "$ARTIFACTS_SECRET"
  bucket: "$S3_BUCKET"
  skip_cleanup: true
  acl: public_read
  local_dir: $HOME/build/sw360/sw360rest/subprojects/resource-server/build/asciidoc/html5